version: '3.8'

services:
  postgres:
    image: postgres:15.4
    container_name: trade_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tradedb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - trade_net

volumes:
  postgres_data:

networks:
  trade_net:
